name: Android Studio Docs Download

on:
  workflow_dispatch:
    inputs:
      docs_url:
        description: 'docsurl'
        required: true
        default: 'https://developer.android.google.cn/studio?hl=zh-cn'


jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
        curl -o webpage.html -e "${{ github.event.inputs.docs_url }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webpage.html
        path: webpage.html
        retention-days: 1


