name: Android Studio Docs Download

on:
  workflow_dispatch:
    inputs:
      docs_url:
        description: 'docsurl'
        required: true
        default: 'https://developer.android.google.cn/studio?hl=zh-cn'
      name:
        description: 'name'
        required: true
        default: 'webpage.html'


jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
        curl -o ${{ github.event.inputs.name }} -L "${{ github.event.inputs.docs_url }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.name }}
        path: ${{ github.event.inputs.name }}
        retention-days: 1


